### ISSUE TITLE
Do we really need PostgreySQL for pushing cf-mta-deploy-service?

### ISSUE THREAD

**Issue by manjunathgudisi** [SAP/cf-mta-deploy-service#127]
HI

Do we really need PostgreSQL for deploying **cf-mta-deploy-service**? Why do we need it and what information it stores? Can't we push the cf-mta-deploy-service without PostgreSQL?

Thanks, Manju

**Comment by manjunathgudisi** [comment]
I just listed out all plugins by executing `cf plugins` command.

<img width="1259" alt="screen shot 2018-03-13 at 2 21 16 pm" src="https://user-images.githubusercontent.com/6059076/37331603-5535851a-26ca-11e8-9b72-ebe6fbb02d17.png">

I already have **deploy-service** there in my canary account by default. At the same time, I dont have PostgreSQL service in my marketplace. 

So, do we really need PostgreSQL???

**Comment by mptsonev** [comment]
Hi Manju,

The Deploy Service operates on top of the Activiti engine, which highly relies on a DB connection. We also store historical data, reusable configurations and other in the DB. Do you want to use a custom deployment of the Deploy Service in your space, rather than using the central one available?

Having the plugin installed doesn't mean that you have a Deploy Service instance in your space. There is a central Deploy Service instance, which can be reached and used with the help of the MtaPlugin.

Best,
Mihail
